/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * HSE = 8 MHz
 * HSI = 16 MHz
 *
 * PLL (Phase Locked Loop)
 * 	|          |         |
 * PLL-M     PLL-N		PLL-P
 *
 * System Clock(SYSCLK) = ((HSE / PLL-M) * PLL-N) / PLL-P
 */

#include <stdint.h>
#include "main.h"
#include "Clock.h"
#include "Gpio.h"

__attribute__((weak)) void _close(void){}
__attribute__((weak)) void _lseek(void){}
__attribute__((weak)) void _read(void){}
__attribute__((weak)) void _write(void){}

extern uint32_t SystemCoreClock;

uint32_t systemClock;

void Delay (uint32_t time)
{
	while (time--);
}

int main(void)
{
	SysClockConfig();
	Discovery_Onboard_Leds_Config();
	Discovery_Onboard_Button_Config();

	while(1)
	{
		if((GPIOA->IDR & (1 << 0)))
		{
			while((GPIOA->IDR & (1 << 0)));
			GPIOD->ODR |= (1 << 12) | (1 << 13) | (1 << 14) | (1 << 15);
			Delay(10000000);
			GPIOD->ODR &= ~((1 << 12) | (1 << 13) | (1 << 14) | (1 << 15));
			Delay(10000000);
		}
	}
}
