/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * HSE = 8 MHz
 * HSI = 16 MHz
 *
 * PLL (Phase Locked Loop)
 * 	|          |         |
 * PLL-M     PLL-N		PLL-P
 *
 * System Clock(SYSCLK) = ((HSE / PLL-M) * PLL-N) / PLL-P
 */

#include <stdint.h>
#include "main.h"
#include "Clock.h"

__attribute__((weak)) void _close(void){}
__attribute__((weak)) void _lseek(void){}
__attribute__((weak)) void _read(void){}
__attribute__((weak)) void _write(void){}

extern uint32_t SystemCoreClock;

uint32_t systemClock;

int main(void)
{
	systemClock = SystemCoreClock;

	SysClockConfig();

	SystemCoreClockUpdate();

	systemClock = SystemCoreClock;

	for(;;);
}
